db:
  build: postgres/
  ports:
    - "5432:5432"
  environment:
    POSTGRES_PASSWORD: changeme
    POSTGRES_USER: postgres
    POSTGRES_DB: test
  labels:
    com.joyent.package: g4-highcpu-128M
    triton.cns.services: test.db

pgrest:
  build: postgrest/
  ports:
    - "3000:3000"
  labels:
    com.joyent.package: g4-highcpu-512M
    triton.cns.services: test.pgrest
